const STATES = {
  DISCOVERY: "DISCOVERY",
  QUALIFICATION: "QUALIFICATION",
  OFFER_CONSULTATION: "OFFER_CONSULTATION",
  COLLECT_EMAIL: "COLLECT_EMAIL",
  COLLECT_NAME: "COLLECT_NAME",
  SHOW_SLOTS: "SHOW_SLOTS",
  BOOKING: "BOOKING",
  COMPLETED: "COMPLETED",
  RESCHEDULE: "RESCHEDULE",
  CONFIRM_CANCEL: "CONFIRM_CANCEL",
  RESCHEDULE_SLOTS: "RESCHEDULE_SLOTS",
  CANCELLED: "CANCELLED",
};

module.exports = STATES;